name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
        # Install other dependencies if needed

    - name: Build and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./run_tests

